package com.pm.fraudservice.model;

public enum FraudType {
    EXCESSIVE_WITHDRAWAL_AMOUNT,
    EXCESSIVE_WITHDRAWAL_FREQUENCY,
    SUSPICIOUS_TRANSFER_PATTERN,
    UNUSUAL_LOCATION,
    RAPID_TRANSACTIONS,
    ACCOUNT_TAKEOVER
}