server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        # Account Service Routes
        - id: account-service
          uri: http://account-service:5000
          predicates:
            - Path=/api/accounts/**
          filters:
            - StripPrefix=1
            
        # Customer Service Routes
        - id: customer-service
          uri: http://customer-service:5001
          predicates:
            - Path=/api/customers/**
          filters:
            - StripPrefix=1
            
        # Transaction Service Routes
        - id: transaction-service
          uri: http://transaction-service:5002
          predicates:
            - Path=/api/transactions/**
          filters:
            - StripPrefix=1
            
        # Auth Service Routes
        - id: auth-service
          uri: http://auth-service:5004
          predicates:
            - Path=/api/auth/**
          filters:
            - StripPrefix=1
      
      # Global CORS configuration
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            exposedHeaders:
              - Content-Type
              - Authorization
            allowCredentials: false
            maxAge: 3600
      
      # Default filters for all routes
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials

# Actuator endpoints for health checks
management:
  endpoints:
    web:
      exposure:
        include: health,info,routes
  endpoint:
    health:
      show-details: always

# Logging configuration
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web.reactive.function.client: TRACE